version: "3.9"

services:
  user-management:
    build: .
    container_name: user-management
    ports:
      - "5255:5255"
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis
    networks:
      - skynetrix-network
    volumes:
      - ./logs:/app/logs # optional, if you're using local log persistence

  mongodb:
    image: mongo:latest
    container_name: user-management-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo-data:/data/db
    networks:
      - skynetrix-network

  redis:
    image: redis:alpine
    container_name: user-management-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - skynetrix-network

networks:
  skynetrix-network:
    driver: bridge

volumes:
  mongo-data:
