// utils/generalRoleOptions.js

module.exports = {
  Shop: [
    "Operator",
    "Technician",
    "Service Advisor",
    "Shop Manager",
    "Customer Service",
    "Receptionist",
    "Employee",
    "Customer",
    "Other",
  ],
  Agency: [
    "Marketing Strategist",
    "SEO Specialist",
    "Content Creator",
    "Ad Specialist",
    "Project Manager",
    "Account Manager",
    "Creative Director",
    "Employee",
    "Other",
  ],
  Vendor: [
    "Sales Representative",
    "Account Manager",
    "Customer Support",
    "Product Specialist",
    "Logistics Coordinator",
    "Integration Engineer",
    "Channel Partner Lead",
    "Employee",
    "Other",
  ],
  Fleet: [
    "Fleet Manager",
    "Driver",
    "Maintenance Coordinator",
    "Scheduler",
    "Dispatcher",
    "Employee",
    "Other",
  ],
  Partner: [
    "Strategic Lead",
    "Partner Manager",
    "Business Liaison",
    "Implementation Specialist",
    "Solutions Consultant",
    "Client Success Partner",
    "Integration Advisor",
    "Employee",
    "Other",
  ],
  Reseller: [
    "Sales Partner",
    "Onboarding Specialist",
    "Channel Manager",
    "Support Representative",
    "Regional Lead",
    "Training Coordinator",
    "Account Executive",
    "Employee",
    "Other",
  ],
  PlatformAdmin: [
    "System Admin",
    "Platform Engineer",
    "DevOps Specialist",
    "Compliance Officer",
    "Internal Support",
    "Product Manager",
    "QA Analyst",
    "Employee",
    "Other",
  ],
  APIOnly: [
    "Integration Engineer",
    "API Developer",
    "Automation Specialist",
    "DevOps Lead",
    "System Architect",
    "Security Engineer",
    "API Product Manager",
    "Employee",
    "Other",
  ],
  Enterprise: [
    "Program Director",
    "Technical Program Manager",
    "Operations Director",
    "Compliance Manager",
    "Executive Assistant",
    "IT Administrator",
    "Business Analyst",
    "Employee",
    "Other",
  ],
};
